import type { JobSource } from '@prisma/client';
import type { IJobSource, SourceCapabilities } from './types';

// ─────────────────────────────────────────────────────────────
// Source Registry — the single authoritative map of
//   JobSource enum value  →  IJobSource implementation
//
// HOW TO ADD A NEW SOURCE
// ──────────────────────
// You do not edit this file. Instead, at the bottom of your
// source file (e.g. src/ingestion/sources/LinkedInJobSource.ts)
// add a single self-registration call:
//
//   registerSource(new LinkedInJobSource());
//
// Then import the file once in src/ingestion/sources/index.ts:
//
//   import './LinkedInJobSource';
//
// That import triggers the side-effect registration automatically.
// The registry, IngestionService, and controller pick it up with
// no further changes.
//
// See HOW_TO_ADD_A_SOURCE.md for the full integration guide.
// ─────────────────────────────────────────────────────────────

const registry = new Map<JobSource, IJobSource>();

// ── Public API ───────────────────────────────────────────────

/**
 * Register a job source implementation.
 *
 * Called as a side-effect at the bottom of each source file so that a
 * bare `import './MyJobSource'` is enough to activate the source.
 *
 * @throws {Error} if another source is already registered for the same
 *   `JobSource` value — duplicate registrations are always a bug.
 */
export function registerSource(source: IJobSource): void {
  const key = source.source;

  if (registry.has(key)) {
    throw new Error(
      `[SourceRegistry] Duplicate registration: a handler for "${key}" is already registered. ` +
      `Each JobSource value may only have one active implementation.`,
    );
  }

  registry.set(key, source);
}

/**
 * Retrieve the handler for a given JobSource.
 *
 * @throws {Error} with a clear message when no handler is registered,
 *   directing the developer to HOW_TO_ADD_A_SOURCE.md.
 */
export function getSource(source: JobSource): IJobSource {
  const handler = registry.get(source);

  if (!handler) {
    throw new Error(
      `[SourceRegistry] No handler registered for source "${source}". ` +
      `Create an implementation in src/ingestion/sources/ and import it in ` +
      `src/ingestion/sources/index.ts. See HOW_TO_ADD_A_SOURCE.md for details.`,
    );
  }

  return handler;
}

/**
 * Returns every JobSource value that currently has a registered handler,
 * regardless of whether the source is enabled.
 */
export function getRegisteredSources(): JobSource[] {
  return [...registry.keys()];
}

/**
 * Returns only the sources whose `capabilities.enabled` flag is true.
 * Use this when you want to run ingestion against all live/ready sources.
 */
export function getEnabledSources(): JobSource[] {
  return [...registry.entries()]
    .filter(([, src]) => src.capabilities.enabled)
    .map(([key]) => key);
}

/**
 * Returns the capabilities descriptor for every registered source.
 * Surfaced by GET /api/v1/ingestion/capabilities so the UI and scheduler
 * can make informed decisions without fetching real data.
 */
export function getAllCapabilities(): Record<string, SourceCapabilities> {
  const out: Record<string, SourceCapabilities> = {};

  for (const [key, src] of registry.entries()) {
    out[key] = src.capabilities;
  }

  return out;
}

/**
 * Check whether a handler is registered for the given source.
 * Useful in guards before calling getSource().
 */
export function hasSource(source: JobSource): boolean {
  return registry.has(source);
}
